repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.13.5
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
  - repo: local
    hooks:
      - id: update GCP Secret
        name: load_settings
        entry: python load_settings.py $PROJECT_NUMBER
        language: system
        types: [ python ]
